services:
  sellasist-nginx:
    image: nginx:stable-alpine
    depends_on:
      - sellasist-php
    networks:
      - sellasist-project
    volumes:
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"

  sellasist-php:
    build:
      context: .docker/
    volumes:
      - ".:/var/www/html"
    networks:
      - sellasist-project

networks:
  sellasist-project:
    external: true